name: integration_test_example
description: Demonstrates how to use the integration_test plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.6.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: any
  integration_test_macos:
    path: ../integration_test_macos
#  test: any
  pedantic: ^1.8.0

  flutter_gherkin:
    git:
      url: https://github.com/jonsamwell/flutter_gherkin
      ref: ef04fa338678ffb59833ebf6affdff2189a8a21c

  build_runner: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
